services:

  api:
    image: ciceroreis/python3:v1
    container_name: api
    user: ${UID}:${GID}
    ports:
      - "8001:8000"
    volumes:
      - ./app:/application
    working_dir: /application
    depends_on:
      - mysql
    command: python -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - super_store_network
  streamlit:
    image: ciceroreis/python3:v1
    container_name: streamlit
    user: ${UID}:${GID}
    ports:
      - "8002:8501"
    volumes:
      - ./dashboard:/application
    working_dir: /application
    depends_on:
      - mysql
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0
    networks:
      - super_store_network
  nginx:
    image: ciceroreis/nginx:v1
    container_name: nginx_proxy
    ports:
      - "80:80"
    depends_on:
      - api
      - streamlit
    networks:
      - super_store_network
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db_super_store
    volumes:
      - super_store_data:/var/lib/mysql
      - ./mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql
    restart: unless-stopped
    networks:
      - super_store_network

networks:
  super_store_network:
    name: super_store_network
    driver: bridge

volumes:
  super_store_data:
    name: super_store_data
    driver: local